# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'windows-latest'

jobs:
  - job: FirstJob
    timeoutInMinutes: 10
    steps:
    - bash: echo "The First Job"

  - job: SecondJob
    steps:
      - bash: echo "Our second Pipeline"
